In [2]:
aList = ["John", 33, "Toronto", True]
print(aList)

['John', 33, 'Toronto', True]


In [3]:
import datetime
tanggal = datetime.datetime.now()
mahasiswa = ["Stanley Alexsander Tamboto", 2022071008, "Informatika", "Desain Analisis Algoritma", tanggal.strftime("%d-%m-%Y"), "Universitas Pembangunan Jaya"]

print(mahasiswa)

['Stanley Alexsander Tamboto', 2022071008, 'Informatika', 'Desain Analisis Algoritma', '13-09-2023', 'Universitas Pembangunan Jaya']


In [4]:
bin_colors = ["Red", "Green", "Blue", "Yellow"]
bin_colors[1]

'Green'

In [ ]:
print("Nama:", mahasiswa[1])

Nama: 2022071008


In [ ]:
print("Universitas:", mahasiswa[-1])

Universitas: Universitas Pembangunan Jaya


In [5]:
bin_colors[0:2]

['Red', 'Green']

In [ ]:
print("Nim dan Prodi:", mahasiswa[1:3])

Nim dan Prodi: [2022071008, 'Informatika']


In [6]:
for aColor in bin_colors:
  print(aColor + " Square")

Red Square
Green Square
Blue Square
Yellow Square


In [ ]:
for i in mahasiswa:
  print(str(i) + " Square")

Stanley Alexsander Tamboto Square
2022071008 Square
Informatika Square
Desain Analisis Algoritma Square
13-09-2023 Square
Universitas Pembangunan Jaya Square


In [ ]:
for i in mahasiswa:
  print("UPJ " + str(i))

UPJ Stanley Alexsander Tamboto
UPJ 2022071008
UPJ Informatika
UPJ Desain Analisis Algoritma
UPJ 13-09-2023
UPJ Universitas Pembangunan Jaya


In [8]:
tuple_bin_colors = ("Red", "Green", "Blue", "Yellow")
bin_colors[1]
bin_colors[2:]

['Blue', 'Yellow']

In [ ]:
UPJ = ("Universitas", "Pembangunan", "Jaya")

print(UPJ)

('Universitas', 'Pembangunan', 'Jaya')


In [9]:
hariAwal = ("senin", "selasa", "rabu")
hariAkhir = ("kamis", "jumat", "sabtu")

hari = (hariAwal, hariAkhir)
print(hari)

(('senin', 'selasa', 'rabu'), ('kamis', 'jumat', 'sabtu'))


In [10]:
pertama = (100)
kedua = (200, 400, 600)
ketiga = (300)
keempat = (400, 800)
nested_tuple = (pertama, kedua, ketiga, keempat)

print(nested_tuple)

(100, (200, 400, 600), 300, (400, 800))


In [12]:
dict_bin_colors = {
    "manual_color" : "Yellow",
    "approved_color" : "Green",
    "refused_color" : "Red"
}

print(dict_bin_colors)

{'manual_color': 'Yellow', 'approved_color': 'Green', 'refused_color': 'Red'}


In [15]:
print(dict_bin_colors.get("approved_color"))
dict_bin_colors["approved_color"]

Green


'Green'

In [17]:
dict_bin_colors["approved_color"] = "Purple"
print(dict_bin_colors)

{'manual_color': 'Yellow', 'approved_color': 'Purple', 'refused_color': 'Red'}


In [ ]:
dictMahasiswa = {"Nama":"Stanley Alexsander Tamboto", "NIM":"2022071008", "Prodi":"Informatika", "Universitas":"UPJ"}

print(dictMahasiswa)
print(dictMahasiswa["Nama"])

{'Nama': 'Stanley Alexsander Tamboto', 'NIM': '2022071008', 'Prodi': 'Informatika', 'Universitas': 'UPJ'}
Stanley Alexsander Tamboto


In [18]:
acak = (True, {"name": "depotkode", "status": "alive"}, [1, 2, 3])
print(acak)

(True, {'name': 'depotkode', 'status': 'alive'}, [1, 2, 3])


In [19]:
green = {"grass", "leaves"}
print(green)

{'leaves', 'grass'}


In [ ]:
#Inisiasi Set
set_01 = {4,5,6,2}
print("set_01 = ", set_01)

#inisiasi mengubah list menjadi set
set_02 = set()
set_03 = set([2,1,4,3])

print(type(set_02))
print("set_03 = ", set_03)

print("\nmenambah")
set_01.add(576)
print(set_01)

print("\nmenghapus")
set_01.discard(6)
print(set_01)

print("\nunion")
print(set_01|set_03)

print("\nintersection")
print(set_01&set_03)

print("\ndifference")
print(set_01-set_03)

print("\nsymmetric difference")
print(set_01^set_03)

set_01 =  {2, 4, 5, 6}
<class 'set'>
set_03 =  {1, 2, 3, 4}

menambah
{576, 2, 4, 5, 6}

menghapus
{576, 2, 4, 5}

union
{576, 1, 2, 3, 4, 5}

intersection
{2, 4}

difference
{576, 5}

symmetric difference
{576, 1, 3, 5}


In [20]:
red = {"dandelions", "leaves", "fire hydrant"}
green = {"rose", "blood", "leaves", "fire hydrant"}

print(red|green)
print(red&green)

{'dandelions', 'leaves', 'rose', 'fire hydrant', 'blood'}
{'leaves', 'fire hydrant'}


In [23]:
import pandas as pd

df = df = pd.DataFrame([
    ['1', 'Fares', 32, True],
     ['2', 'Elena', 23, False],
      ['3', 'Steven', 40, True]
])

In [24]:
df.columns = ["id", "name", "age", "decision"]
df

id    name  age  decision
0  1   Fares   32      True
1  2   Elena   23     False
2  3  Steven   40      True

In [34]:
df[["name", "age"]]

name  age
0   Fares   32
1   Elena   23
2  Steven   40

In [35]:
df.iloc[:,3]

0     True
1    False
2     True
Name: decision, dtype: bool

In [32]:
df.iloc[1:3,:]

id    name  age  decision
1  2   Elena   23     False
2  3  Steven   40      True

In [33]:
df[df.age>30]

id    name  age  decision
0  1   Fares   32      True
2  3  Steven   40      True

In [36]:
df[(df.age < 35) & (df.decision == True)]

id   name  age  decision
0  1  Fares   32      True

In [37]:
data = {
    'satu': [1,1,1,1,1],
    'dua' : [2,2,2,2,2],
    'tiga': [3,3,3,3,3]
    }
df = pd.DataFrame(data, index=['a','b','c','d','e'])
df.head()

satu  dua  tiga
a     1    2     3
b     1    2     3
c     1    2     3
d     1    2     3
e     1    2     3

In [ ]:
df = pd.DataFrame([
    [1, "Informatika", 50, 30, 20],
    [2, "Sistem Informasi", 55, 30, 25],
    [3, "Teknik Sipil", 40, 30, 10]
])

df.columns = ["No", "Prodi", "Mahasiswa", "laki-laki", "Perempuan"]
df.style.hide(axis='index')

In [41]:
import numpy as np

myMatrix = np.array([[11, 12, 13], [21, 22, 23], [31, 32, 33]])
print(myMatrix)
print(type(myMatrix))

[[11 12 13]
 [21 22 23]
 [31 32 33]]
<class 'numpy.ndarray'>


In [42]:
matriksC = np.array([[1,2,3], [4,5,6]])
print("Matriks C : ")
print(matriksC)

transpose_matriks = np.transpose(matriksC)
print("Tranpose Matriks C : ")
print(transpose_matriks)

Matriks C : 
[[1 2 3]
 [4 5 6]]
Tranpose Matriks C : 
[[1 4]
 [2 5]
 [3 6]]


In [40]:
matrix = np.array([
    [100, 200, 300],
    [700, 600, 500],
    [900, 1000, 800]
    ])

print(matrix)

print("\nTranspose:")
print(matrix.T)

[[ 100  200  300]
 [ 700  600  500]
 [ 900 1000  800]]

Transpose:
[[ 100  700  900]
 [ 200  600 1000]
 [ 300  500  800]]


In [43]:
myVector = [22,33,44,55]
print(myVector)
print(type(myVector))

[22, 33, 44, 55]
<class 'list'>


In [44]:
myVector = np.array([22,33,44,55])
print(myVector)
print(type(myVector))

[22 33 44 55]
<class 'numpy.ndarray'>


In [48]:
class Stack:
  def __init__(self):
    self.items = []
  def isEmpty(self):
    return self.items == []
  def push(self, item):
    self.items.append(item)
  def pop(self):
    return self.items.pop()
  def peek(self):
    return self.items[len(self.items)-1]
  def size(self):
    return len(self.items)

In [49]:
stack = Stack()
stack.push("Red")
stack.push("Green")
stack.push("Blue")
stack.push("Yellow")

In [50]:
stack.pop()

'Yellow'

In [52]:
stack.isEmpty()

False

In [53]:
class Queue(object):
  def __init__(self):
    self.items = []
  def isEmpty(self):
    return self.items == []
  def enqueue(self, item):
    self.items.insert(0, item)
  def dequeue(self):
    return self.items.pop()
  def size(self):
    return len(self.items)

In [55]:
queue = Queue()
queue.enqueue("Red")
queue.enqueue("Green")
queue.enqueue("Blue")
queue.enqueue("Yellow")

In [56]:
print(queue.size())

4


In [57]:
print(queue.dequeue())

Red


In [58]:
print(queue.dequeue())

Green


In [61]:
class Node:
  def __init__(self,data):
    self.left = None
    self.right = None
    self.data = data
  def PrintTree(self):
    if self.left:
      self.left.PrintTree()
    print( self.data),
    if self.right:
      self.right.PrintTree()

In [62]:
root = Node(2)#root
root.left = Node(3) #child kiri dari root
root.right = Node(5) #child kanan dari root
root.left.left = Node(7) #child kiri dari 3
root.left.right = Node(9) #child kanan dari 3
root.right.left = Node(11) #child kiri dari 5
root.right.right = Node(13) #child kanan dari 5
root.PrintTree()

7
3
9
2
11
5
13
